name: CI

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  buildWindows:
    name: MetaUnion
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Packages/packages-lock.json', 'Packages/manifest.json', 'ProjectSettings/ProjectVersion.txt', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildsPath: build
          buildName: MetaUnion

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MetaUnion
          path: build

      - name: Zip build
        shell: pwsh
        run: |
          Compress-Archive -Path build\* -DestinationPath MetaUnion.zip -Force
      
      - name: Create GitHub Release & Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: MetaUnion.zip
